mode: daemonset
hostNetwork: true
service:
  enabled: true
presets:
  hostMetrics:
    enabled: true
  logsCollection:
    enabled: true
    includeCollectorLogs: false
    storeCheckpoints: true
  kubernetesAttributes:
    enabled: true
  #   extractAllPodLabels: false
  #   extractAllPodAnnotations: false
  kubeletMetrics:
    enabled: true
extraEnvsFrom:
  - secretRef:
      name: datadog-us1
tolerations:
  - key: node-role.kubernetes.io/control-plane
    operator: Exists
    effect: NoSchedule
config:
  connectors:
    # https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/connector/datadogconnector
    datadog/connector:
      # https://docs.datadoghq.com/tracing/guide/inferred-service-opt-in/?tab=java#opentelemetry-collector
      traces:
        compute_stats_by_span_kind: true
        peer_tags_aggregation: true
        peer_tags: ["_dd.base_service","amqp.destination","amqp.exchange","amqp.queue","aws.queue.name","bucketname","cassandra.cluster","db.cassandra.contact.points","db.couchbase.seed.nodes","db.hostname","db.instance","db.name","db.system","grpc.host","hazelcast.instance","hostname","http.host","messaging.destination","messaging.destination.name","messaging.kafka.bootstrap.servers","messaging.rabbitmq.exchange","messaging.system","mongodb.db","msmq.queue.path","net.peer.name","network.destination.name","peer.hostname","peer.service","queuename","rpc.service","rpc.system","server.address","streamname","tablename","topicname"]    
  receivers:
    kubeletstats:
      insecure_skip_verify: true
  processors:
    resourcedetection:
      detectors: [system,ec2]
      timeout: 2s
      override: false
    attributes:
      actions:
        - key: env
          action: upsert
          value: otel
        - key: otel.source
          action: upsert
          value: daemonset-otel
    batch:
      timeout: 2s
  exporters:
    datadog:
      api:
        site: ${env:DD_SITE}
        key: ${env:DD_API_KEY}
  service:
    pipelines:
      metrics:
        receivers:
          - otlp
          - datadog/connector
        processors:
          - resourcedetection
          - attributes
          - batch
        exporters:
          - datadog
      logs:
        processors:
          - resourcedetection
          - attributes
          - batch
        exporters:
          - datadog
      traces:
        receivers:
          - otlp
        processors:
          - resourcedetection
          - attributes
          - batch
        exporters:
          - datadog/connector
      traces/2:
        receivers:
          - datadog/connector
        processors:
          - batch
        exporters:
          - datadog
