apiVersion: v1
kind: Pod
metadata:
  name: loadrunner
  namespace: developer-app
  labels:
    app.kubernetes.io/name: loadrunner
    admission.datadoghq.com/enabled: "false"
    tags.datadoghq.com/env: lab
    tags.datadoghq.com/service: loadrunner
    tags.datadoghq.com/version: "0.0"
spec:
  containers:
    - name: load
      image: yaalexf/toolbox:alpine
      imagePullPolicy: Always
      command: ["sh", "-c", "--"]
      args:
        - |-
          while true
          do
            wget -qO /dev/nul http://developer-app/process/payment
            sleep 10s
          done &

          while true
          do
            curl -sX PUT \
              http://developer-app/collection/create
            sleep 10m
          done &

          while true
          do
            curl -sX PUT \
              http://developer-app/collection/add/foo
            sleep 5s
          done &

          while true
          do
            curl -sX PATCH \
              http://developer-app/collection/shuffle
            sleep 1s
          done &

          while true
          do
            curl -sX PATCH \
              http://developer-app/collection/sort
            sleep 5s
          done &

          while true
          do
            sleep 60s
            curl -sX DELETE \
              http://developer-app/collection/drain?percentage=20
          done &

          while true
          do
            sleep 1s
            curl -sX PUT \
              -H 'Content-Type: application/json' \
              -d '{"foo":"bar"}' \
              http://developer-app/kafka/produce
          done &

          while true
          do
            sleep 2s
            curl -qO /dev/nul -sX GET \
              http://developer-app/mysql/simple_query
          done &

          while true
          do
            sleep 10s
            curl -qO /dev/nul -sX GET \
              http://developer-app/mysql/simple_join
          done &

          sleep 1d
      resources:
        limits: {}
